"""
    AT Command class definition
    Authors : Iheb Omar Soula and Nadir Hermassi
    telecommunications Engineering Students @ SUPCOM [ HIGHER SCHOOL OF COMMUNICATIONS OF TUNIS]
    Project in Sup'Com with Comelit R&D company
    date: 12/10/2021
"""
class AT_COMMANDS:

    def __init__(self,atcommand):
        self.string=atcommand


    def __eq__(self,other):
        if (self.atcommand==other.atcommand):
            return True
        else:
            return False
    def __ne__(self,other):
        if(self.atcommand!=other.atcommand):
            return True
        else:
            return False

        

''' 

AT Command list 

'''

TURN_OFF = AT_COMMANDS("AT+QPOWD\r\n")
NOTHING=AT_COMMANDS("\r\n")
MANIFACTURE_ID = AT_COMMANDS("AT+GMI\r\n")
DEVICE_ID= AT_COMMANDS("AT+CGMM\r\n")
FIRMWARE_VS= AT_COMMANDS("AT+GMR\r\n")
REGISTRED_DEVICE_STATUS = AT_COMMANDS("AT+CGREG\r\n")
NETWORK_NAME=AT_COMMANDS("AT+QSPN\r\n")
PREFERED_OPERATORS_LIST = AT_COMMANDS("AT+CPOL\r\n")
DELETE_SMS=AT_COMMANDS("AT+CMGD=\r\n")
SIM_CARD_IMSI= AT_COMMANDS("AT+CIMI\r\n")
SIM_CARD_ICCID=AT_COMMANDS("AT+QCCID\r\n")
SIM_CARD_INIT= AT_COMMANDS("AT+QINISTAT\r\n")
GET_SMS_MODE=AT_COMMANDS("AT+CMGF?\r\n")
SET_SMS_MODE=AT_COMMANDS("AT+CMGF=\r\n")
EXTENDED_CONF_SET=AT_COMMANDS("AT+QCFG\r\n")
SET_SMS_CHAR=AT_COMMANDS("AT+CSCS=\r\n")
SEND_SMS_NUMBER=AT_COMMANDS("AT+CMGS=\r\n")
GET_SMS_STORAGE_AREA=AT_COMMANDS("AT+CPMS?\r\n")
SET_SMS_STORAGE_AREA=AT_COMMANDS("AT+CPMS=\r\n")
READ_SMS_LIST=AT_COMMANDS("AT+CMGL=\r\n")
CALL_NUMBER=AT_COMMANDS("ATD\r\n")
DISCONNECT_NUMBER=AT_COMMANDS("ATH\r\n")
HUNG_UP_CALL=AT_COMMANDS("AT+CHUP\r\n")
CANCEL_CALL=AT_COMMANDS("ATH\r\n")
ANSWER_CALL=AT_COMMANDS("ATA\r\n")
OPEN_NETWORK_MQTT=AT_COMMANDS("AT+QMTOPEN=")
CLOSE_NETWORK_MQTT=AT_COMMANDS("AT+QMTCLOSE=")
CONNECT_MQTT=AT_COMMANDS("AT+QMTCONN=")
DISCONNECT_MQTT=AT_COMMANDS("AT+QMTDISC=")
SUBSCRIBE_MQTT=AT_COMMANDS("AT+QMTSUB=")
UNSUBSCRIBE_MQTT=AT_COMMANDS("AT+QMTSUB=")
PUBLISH_MQTT=AT_COMMANDS("AT+QMTPUBX=")
READ_MSG_MQTT=AT_COMMANDS("AT+QMTRECV=")
SMS_EVT_RP_CONF=AT_COMMANDS("AT+CNMI=\r\n")


